apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-clearsession
spec:
  startingDeadlineSeconds: 40
  schedule: "0 0 1 * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-clearsessions
              image: {{ .Values.container.image }}
              command: [ "python" ]
              args: [ "manage.py", "clearsessions" ]
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
              env:
                - name: DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: env-config
                      key: DEBUG
          restartPolicy: OnFailure