apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}-migrate
          image: {{ .Values.container.image }}
          command: [ "python" ]
          args: [ "manage.py", "migrate" ]
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DEBUG
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DATABASE_URL
      restartPolicy: Never