apiVersion: v1
kind: Service
metadata:
  name : {{ .Release.Name }}-service
  labels:
    env   : prod
    owner : Aleksei_Ushakov
spec:
  selector  :
    project : {{ .Release.Name }} # select PODs with this labels
  ports:
    - name       : {{ .Release.Name }}-listener
      protocol   : TCP
      port       : 80 # port on ClusterIP
      targetPort : 80 # port on POD
  type: ClusterIP