apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-clearsession
spec:
  schedule: "0 0 1 * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: django_app:latest
              command: [ "python" ]
              args: [ "manage.py", "clearsessions" ]
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
              env:
                - name: DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: env-config
                      key: DEBUG
          restartPolicy: OnFailure