apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: edu-desperate-sinoussi
  uid: 1e5ae842-909a-4f26-8feb-a42efb299df3
  resourceVersion: '114389285'
  creationTimestamp: '2024-05-06T09:40:35Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-service","namespace":"edu-desperate-sinoussi"},"spec":{"ports":[{"nodePort":30341,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx","k8slens-edit-resource-version":"v1","owner":"statik2002"},"type":"NodePort"}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2024-05-06T09:40:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
  selfLink: /api/v1/namespaces/edu-desperate-sinoussi/services/nginx-service
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30341
  selector:
    app: nginx
    k8slens-edit-resource-version: v1
    owner: statik2002
  clusterIP: 10.98.145.149
  clusterIPs:
    - 10.98.145.149
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
